# Generated by Django 5.0.4 on 2024-04-30 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Normal_question',
        ),
        migrations.DeleteModel(
            name='Pattern_question',
        ),
    ]
