# Generated by Django 5.0.4 on 2024-04-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions_module', '0002_delete_admin_delete_normal_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Normal_question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('question_name', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=500)),
                ('a', models.CharField(max_length=100)),
                ('b', models.CharField(max_length=100)),
                ('c', models.CharField(max_length=100)),
                ('d', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pattern_question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('question_name', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=500)),
                ('question_image', models.CharField(max_length=100)),
                ('a', models.CharField(max_length=100)),
                ('b', models.CharField(max_length=100)),
                ('c', models.CharField(max_length=100)),
                ('d', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
