# Generated by Django 5.0.4 on 2024-05-07 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0004_session_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolls',
            fields=[
                ('enroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('enroll_types', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_types', models.CharField(max_length=100)),
                ('enroll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions_module.enrolls')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_types', models.CharField(max_length=100)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions_module.classes')),
            ],
        ),
    ]
