# Generated by Django 5.0.4 on 2024-05-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0005_enrolls_classes_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normal_question',
            name='age',
        ),
        migrations.RemoveField(
            model_name='pattern_question',
            name='age',
        ),
        migrations.AddField(
            model_name='normal_question',
            name='enroll_type',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pattern_question',
            name='enroll_type',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
