# Generated by Django 5.0.4 on 2024-05-13 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0006_remove_normal_question_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='enroll_id',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='questions_module.enrolls'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrolls',
            name='enroll_types',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
