# Generated by Django 5.0.4 on 2024-05-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0008_alter_enrolls_enroll_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolls',
            name='enroll_types',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
