# Generated by Django 5.0.4 on 2024-05-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0011_alter_enrolls_enroll_id_alter_subjects_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolls',
            name='enroll_id',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
    ]
