# Generated by Django 5.0.4 on 2024-05-13 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0014_alter_enrolls_enroll_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='enroll_id',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='enroll_id',
        ),
        migrations.DeleteModel(
            name='Normal_question',
        ),
        migrations.DeleteModel(
            name='Pattern_question',
        ),
        migrations.DeleteModel(
            name='Session_table',
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='Enrolls',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
