# Generated by Django 5.0.4 on 2024-05-13 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions_module', '0015_delete_admin_remove_classes_enroll_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolls',
            fields=[
                ('enroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('enroll_types', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Normal_question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('enroll_type', models.CharField(max_length=100)),
                ('question_name', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=500)),
                ('a', models.CharField(max_length=100)),
                ('b', models.CharField(max_length=100)),
                ('c', models.CharField(max_length=100)),
                ('d', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern_question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('enroll_type', models.CharField(max_length=100)),
                ('question_name', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=500)),
                ('question_image', models.CharField(max_length=100)),
                ('a', models.CharField(max_length=100)),
                ('b', models.CharField(max_length=100)),
                ('c', models.CharField(max_length=100)),
                ('d', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Session_table',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_types', models.CharField(max_length=100)),
                ('enroll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions_module.enrolls')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_types', models.CharField(max_length=100)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions_module.classes')),
                ('enroll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions_module.enrolls')),
            ],
        ),
    ]
